var initializeGame = require('./initializeGame');
initializeGame("abc",[
	{"question1":"Who is sachin tendulkar?"},
	{"question2":"Start spreading the news, I’m leaving today” are the opening lines of which song?"},
	{"question3":'In which television programme was I don’t believe it a catchphrase?'},
	{"question4":'You Give Love a Bad Name and Livin’ on a Prayer were early hits for which band?'},
	{"question5":'What was the surname of Del Boy and Rodney in Only Fools and Horses?'},
	{"question6":'In which year was a cinematic Space Odyssey set?'},
	{"question7":'Who was the lead singer of T. Rex?'},
	{"question8":'Which silent movie actor created “The Little Tramp” character?'},
	{"question9":'In which film does the line “Toto, I’ve a feeling we’re not in Kansas anymore” appear?'},
	{"question10":'Who plays Lewis in Morse and its spin-off, Lewis?'},
	{"question11":'What is Indiana Jones’s profession?'},
	{"question12":'Which policeman was at the centre of the Pink Panther movies?'},
	{"question13":'Which musical instruments are also called Kettledrums?'},
	{"question14":'Some Enchanted Evening, Happy Talk and There is Nothing Like a Dame are songs from which musical?'},
	{"question15":'Which long-running Australian series is set in Summer Bay?'},
	{"question16":'In which film does a farmer played by Kevin Costner build a baseball diamond in his cornfield?'},
	{"question17":'Fox Mulder and Dana Scully were the main characters in which television series?'},
	{"question18":'Which former schoolteacher from Neath has become a big-selling singer?'},
	{"question19":'Who played Maximus Decimus Meridius in a 2000 Ridley Scott film?'},
	{"question20":'How many red balloons did Nena take into the pop charts?'},
	{"question21":'Which of the Muppets did a stand-up comedy routine which tended not to be particularly good?'},
	{"question22":'In what sort of music might you hear scat singing?'},
	{"question23":'Which television series is set in William McKinley High School, Lima, Ohio?'},
	{"question24":'With which band did Pete Doherty come to fame?'},
	{"question25":'Which soap opera started in 1972, and lost a word from its title in 1989?'},
	{"question26":'What started with Sergeant in 1958 and ended with Columbus in 1992?'},
	{"question27":'What is the name of the character played by Michael Douglas in the Wall Street films?'},
	{"question28":'From which opera does the March of the Toreadors come?'},
	{"question29":'Who played the Vicar of Dibley?'},
	{"question30":'What are the surnames of the title characters in Romeo and Juliet?'}],

	["srini","vishant","lal jose"],[0,0,0]);